services:
  my-db-server:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql_data:/var/lib/mysql
  my-cache-server:
    image: redis
    ports:
      - 6379:6379